name: HTML Linting

on:
  push:
    branches:
      - main
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Linter
        if: contains(github.event.head_commit.message, '[skip lint]') == false # Optional: skip lint if commit contains [skip lint]
        run: |
          python3 -m pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run HTML Linter
        run: |
          npm install -g htmlhint
          htmlhint "**/*.html"  # Lint all HTML files in the repo

      - name: Notify on Failure
        if: ${{ failure() }}
        run: echo "Error; Linting failed! Please check the code for syntax issues."
